# Generated by Django 2.0.7 on 2018-08-02 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=200, verbose_name='考试唯一识别标志符')),
                ('name', models.CharField(max_length=200, verbose_name='考试名称')),
                ('classes', models.CharField(max_length=200, verbose_name='考试对应的班级')),
                ('num_choice', models.PositiveSmallIntegerField(verbose_name='选择题数目')),
                ('point_choice', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题选择题分数')),
                ('tag_choice', models.CharField(max_length=200, verbose_name='选择题题库标签')),
                ('num_completion', models.PositiveSmallIntegerField(verbose_name='填空题数目')),
                ('point_completion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题填空题分数')),
                ('tag_completion', models.CharField(max_length=200, verbose_name='填空题题库标签')),
                ('num_trueorfalse', models.PositiveSmallIntegerField(verbose_name='判断题数目')),
                ('point_trueorfalse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题判断题分数')),
                ('tag_trueorfalse', models.CharField(max_length=200, verbose_name='判断题题库标签')),
                ('num_programcorrection', models.PositiveSmallIntegerField(verbose_name='程序改错题数目')),
                ('point_programcorrection', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题程序改错题分数')),
                ('tag_programcorrection', models.CharField(max_length=200, verbose_name='程序改错题题库标签')),
                ('num_programreading', models.PositiveSmallIntegerField(verbose_name='程序阅读题数目')),
                ('point_programreading', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题程序阅读题分数')),
                ('tag_programreading', models.CharField(max_length=200, verbose_name='程序阅读题题库标签')),
                ('num_programdesign', models.PositiveSmallIntegerField(verbose_name='程序设计题数目')),
                ('point_programdesign', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='每题程序设计题分数')),
                ('tag_programdesign', models.CharField(max_length=200, verbose_name='程序设计题题库标签')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('examname', models.CharField(max_length=200, verbose_name='考试名称')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='总分')),
                ('data', django_mysql.models.JSONField(blank=True, default=dict, null=True, verbose_name='辅助数据（考试题目和用户答案）')),
                ('is_submitted', models.SmallIntegerField(choices=[(0, '未提交'), (1, '已提交')], default=0, verbose_name='是否提交')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Exam', verbose_name='所属考试')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.SmallIntegerField(choices=[(1, '学生'), (2, '教师')], default=1, verbose_name='用户类型')),
                ('classes', models.CharField(max_length=200, verbose_name='班级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.SmallIntegerField(choices=[(0, '选择题'), (1, '填空题'), (2, '判断题'), (3, '程序改错题'), (4, '程序阅读题'), (5, '程序设计题')], verbose_name='题库类型')),
                ('pid', models.PositiveIntegerField(verbose_name='题目编号')),
                ('description', models.TextField(verbose_name='题干描述')),
                ('template', models.TextField(verbose_name='程序模板')),
                ('choice_A', models.CharField(max_length=400, verbose_name='A选项')),
                ('choice_B', models.CharField(max_length=400, verbose_name='B选项')),
                ('choice_C', models.CharField(max_length=400, verbose_name='C选项')),
                ('choice_D', models.CharField(max_length=400, verbose_name='D选项')),
                ('answer', models.CharField(max_length=200, verbose_name='标准答案（除程序改错和设计）')),
                ('test_case_id', models.CharField(max_length=200, verbose_name='测试点id')),
                ('tag', models.CharField(max_length=200, verbose_name='标签')),
            ],
        ),
    ]
